name: Run Web Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  start-web-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start Web Server
      run: |
        nohup node server.js &
        sleep 5
        curl http://localhost:3000
